server {
    listen 80;
    listen [::]:80;
    server_name zhouying.cn;

    root /var/www/zhouying.cn;
    index index.html;
    charset utf-8;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
